---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zed-csi-debug-pvc
  namespace: csi
  labels:
    name: zed-csi-debug
spec:
  storageClassName: 'zed-csi-debug-class'
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zed-csi-debug-pvc-nfs
  namespace: csi
  labels:
    name: zed-csi-debug
spec:
  storageClassName: 'zed-csi-debug-class-nfs'
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi

---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: csi
  labels:
    name: testpod
spec:
  containers:
    - name: redis
      image: redis
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: '/pvc-iscsi'
          name: pvc-path-iscsi
        - mountPath: '/pvc-nfs'
          name: pvc-path-nfs
  volumes:
    - name: pvc-path-iscsi
      persistentVolumeClaim:
        claimName: zed-csi-debug-pvc
    - name: pvc-path-nfs
      persistentVolumeClaim:
        claimName: zed-csi-debug-pvc-nfs
