apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metal-csi.fullname" . }}
  labels:
    {{- include "metal-csi.labels" . | nindent 4 }}
data:
  {{- with .Values.config }}
  metal-csi.yml: |
    {{- toYaml . | nindent 4 }}
  {{- end }}
