apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "metal-csi.fullname" . }}-node
  labels:
    {{- include "metal-csi.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "metal-csi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "metal-csi.selectorLabels" . | nindent 8 }}

    spec:
      hostNetwork: true
      serviceAccountName: {{ include "metal-csi.serviceAccountName" . }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: csi-node-driver-registrar
          image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0
          args:
            {{- include "metal-csi.csiHelperArgs" . | nindent 12 }}
            - '--kubelet-registration-path=/var/lib/kubelet/plugins_registry/metal-csi/csi.sock'
          env:
            {{- include "metal-csi.csiHelperEnv" . | nindent 12 }}
          volumeMounts:
            {{- include "metal-csi.csiHelperVolumeMounts" . | nindent 12 }}

        - name: metal-csi-node
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: [-l, debug, --node-id, $(KUBE_NODE_NAME), --csi-path, /plugin/csi.sock, --csi-name, {{ include "metal-csi.drivername" . }}]
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: plugin-dir
              mountPath: /plugin
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: 'Bidirectional'
            - name: node-root
              mountPath: /node
              mountPropagation: 'Bidirectional'
            - name: metal-csi-yml
              mountPath: /etc/metal-csi.yml
              subPath: metal-csi.yml

      volumes:
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/metal-csi
            type: DirectoryOrCreate

        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory

        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory

        - name: node-root
          hostPath:
            path: /
            type: Directory

        - name: metal-csi-yml
          configMap:
            name: {{ include "metal-csi.fullname" . }}
